"""Writes run artifacts to an immutable run directory.

Layout (matches ARCHITECTURE.md §15)::

    runs/<run-id>/
      manifest.json
      traces/<scenario-id>.json
      evaluations.jsonl
      summary.json
      summary.md
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

from cavbench.reports.markdown import render_ablation_summary, render_run_summary

if TYPE_CHECKING:
    from cavbench.runner import CompletedRun


def write_run(output_dir: Path, run: "CompletedRun") -> Path:
    run_dir = Path(output_dir) / run.run_id
    traces_dir = run_dir / "traces"
    traces_dir.mkdir(parents=True, exist_ok=True)

    (run_dir / "manifest.json").write_text(json.dumps(run.manifest, indent=2, sort_keys=True) + "\n")

    with (run_dir / "evaluations.jsonl").open("w") as f:
        for sid in sorted(run.evaluations):
            f.write(json.dumps(run.evaluations[sid].to_dict(), sort_keys=True) + "\n")

    for sid, trace in run.traces.items():
        (traces_dir / f"{sid}.json").write_text(json.dumps(trace.to_dict(), indent=2, sort_keys=True) + "\n")

    summary = {
        "run_id": run.run_id,
        "manifest": run.manifest,
        "metrics": run.metrics.to_dict(),
    }
    (run_dir / "summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    (run_dir / "summary.md").write_text(render_run_summary(run))
    return run_dir


def write_ablation(output_dir: Path, runs: dict[str, "CompletedRun"], *, profile_order: tuple[str, ...]) -> Path:
    ablation_dir = Path(output_dir)
    ablation_dir.mkdir(parents=True, exist_ok=True)
    for profile_name, run in runs.items():
        write_run(ablation_dir, run)

    summary = {
        "study_type": "controlled architecture ablation",
        "important_limitation": (
            "These results are generated by deterministic architecture profiles, not by an LLM or "
            "production agent. They must not be reported as model performance."
        ),
        "profiles": {
            profile_name: {"run_id": runs[profile_name].run_id, "metrics": runs[profile_name].metrics.to_dict()}
            for profile_name in profile_order
        },
    }
    (ablation_dir / "summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    (ablation_dir / "summary.md").write_text(render_ablation_summary(runs, profile_order=profile_order))
    return ablation_dir
